# Generated by Django 5.0.4 on 2024-05-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uniprot', '0008_multisequencealignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('pdb_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('method', models.TextField()),
                ('uniprot_entries', models.ManyToManyField(related_name='pdb_entries', to='uniprot.entry')),
            ],
        ),
    ]
