# Generated by Django 5.0.4 on 2024-05-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0009_entry_reviewed'),
        ('wpdb', '0003_entryuniprotentry_entry_uniprot_entries'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entryuniprotentry',
            unique_together={('uniprot_entry', 'pdb_entry')},
        ),
    ]
