# Generated by Django 5.0.4 on 2024-04-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATH',
            fields=[
                ('number', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
    ]
