# Generated by Django 5.0.4 on 2024-04-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cath', '0002_rename_cath_superfamily'),
        ('uniprot', '0004_remove_entry_keywords_entry_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperfamilyUniprotEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('evalue', models.FloatField()),
                ('superfamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cath.superfamily')),
                ('uniprot_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniprot.entry')),
            ],
            options={
                'unique_together': {('uniprot_entry', 'superfamily', 'start', 'end')},
            },
        ),
    ]
