# Generated by Django 5.0.4 on 2024-04-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cath', '0003_superfamilyuniprotentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superfamilyuniprotentry',
            name='evalue',
        ),
    ]
