# Generated by Django 5.0.4 on 2024-04-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cath', '0005_superfamily_uniprot_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superfamily',
            name='name',
            field=models.TextField(verbose_name='CATH name'),
        ),
        migrations.AlterField(
            model_name='superfamily',
            name='number',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='CATH number'),
        ),
    ]
