# Generated by Django 5.0.4 on 2024-05-07 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cath', '0007_superfamilyuniprotentry_seq'),
        ('uniprot', '0007_alter_entry_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superfamilyuniprotentry',
            name='seq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uniprot.sequence'),
        ),
    ]
