# Generated by Django 5.0.4 on 2025-03-17 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('taxid', models.IntegerField(primary_key=True, serialize=False, verbose_name='NCBI TaxID')),
                ('rank', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('common_name', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.taxon')),
            ],
            options={
                'verbose_name_plural': 'Taxa',
            },
        ),
    ]
