# Generated by Django 5.0.4 on 2025-03-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_taxon_alternative_taxids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxon',
            old_name='alternative_taxids',
            new_name='old_taxids',
        ),
    ]
