# Generated by Django 5.0.4 on 2024-04-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_deleted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='is_preliminary',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='is_transferred',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
