# Generated by Django 5.0.4 on 2024-04-09 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0003_remove_entry_id_alter_entry_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='ec.entry')),
            ],
            options={
                'unique_together': {('entry', 'name')},
            },
        ),
    ]
