# Generated by Django 5.0.4 on 2024-04-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0004_synonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='systematic_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
