# Generated by Django 5.0.4 on 2024-04-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0006_entryuniprotentry_entry_uniprot_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_preliminary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_transferred',
            field=models.TextField(),
        ),
    ]
