# Generated by Django 5.0.4 on 2024-04-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0007_alter_entry_is_deleted_alter_entry_is_preliminary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='comments',
        ),
    ]
