# Generated by Django 5.0.4 on 2024-04-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0009_rename_is_transferred_entry_transferred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='systematic_name',
        ),
    ]
