# Generated by Django 5.0.4 on 2024-04-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
