# Generated by Django 5.0.4 on 2024-04-08 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_alter_term_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(db_index=True, max_length=255)),
                ('term1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation1', to='eco.term')),
                ('term2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation2', to='eco.term')),
            ],
            options={
                'unique_together': {('term1', 'relation', 'term2')},
            },
        ),
    ]
