# Generated by Django 5.0.4 on 2024-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='taxid',
            field=models.IntegerField(default=0, verbose_name='NCBI TaxId'),
            preserve_default=False,
        ),
    ]
