# Generated by Django 5.0.4 on 2024-04-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0002_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='id',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
