# Generated by Django 5.0.4 on 2024-04-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0002_entry_comment_entry_name_entry_taxid'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='seq',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
