# Generated by Django 5.0.4 on 2024-04-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0003_remove_keyword_id_alter_keyword_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='keywords',
        ),
        migrations.AddField(
            model_name='entry',
            name='keywords',
            field=models.ManyToManyField(related_name='entries', to='uniprot.keyword'),
        ),
    ]
