# Generated by Django 5.0.4 on 2024-04-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0003_entry_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='keywords',
            field=models.JSONField(default=list),
        ),
    ]
