# Generated by Django 5.0.4 on 2024-05-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0004_remove_entry_keywords_entry_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='seq',
        ),
    ]
