# Generated by Django 5.0.4 on 2024-05-07 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0005_sequence_remove_entry_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='seq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uniprot_entries', to='uniprot.sequence'),
        ),
    ]
