# Generated by Django 5.0.4 on 2024-05-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0006_entry_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='seq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uniprot_entries', to='uniprot.sequence'),
        ),
    ]
