# Generated by Django 5.0.4 on 2024-05-08 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0007_alter_entry_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSequenceAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('family', models.TextField()),
                ('alignment', models.TextField()),
                ('seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_sequence_alignments', to='uniprot.sequence')),
            ],
            options={
                'unique_together': {('name', 'family', 'seq')},
            },
        ),
    ]
