# Generated by Django 5.0.4 on 2025-03-13 16:11

import uniprot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0009_entry_reviewed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sequence',
            index=models.Index(uniprot.models.MD5('seq'), name='seq_md5_idx'),
        ),
    ]
