# Generated by Django 5.0.4 on 2025-03-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0010_sequence_seq_md5_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sequence',
            name='seq_md5_idx',
        ),
    ]
