# Generated by Django 5.0.4 on 2025-03-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0011_remove_sequence_seq_md5_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='seq_hash',
            field=models.CharField(default=1, editable=False, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
