# Generated by Django 5.0.4 on 2025-03-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0012_sequence_seq_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='seq',
            field=models.TextField(),
        ),
    ]
