# Generated by Django 5.0.4 on 2025-03-17 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('uniprot', '0013_alter_sequence_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uniprot_entries', to='taxonomy.taxon'),
        ),
    ]
