# Generated by Django 5.0.4 on 2025-03-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0014_entry_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='taxid',
        ),
    ]
