# Generated by Django 5.0.4 on 2025-09-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_rename_alternative_taxids_taxon_old_taxids'),
        ('uniprot', '0016_entry_features'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(condition=models.Q(('reviewed', True)), fields=['reviewed'], name='reviewed_idx'),
        ),
    ]
