# Generated by Django 5.0.4 on 2025-09-23 11:41

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniprot', '0017_entry_reviewed_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sequence',
            index=models.Index(django.db.models.functions.text.Length('seq'), name='idx_seq_len'),
        ),
    ]
