# Generated by Django 5.0.4 on 2024-04-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='description',
            new_name='definition',
        ),
        migrations.RemoveField(
            model_name='term',
            name='namespace',
        ),
        migrations.AddField(
            model_name='term',
            name='aspect',
            field=models.TextField(choices=[('cellular component', 'cellular component'), ('biological process', 'biological process'), ('molecular function', 'molecular function')], default=''),
            preserve_default=False,
        ),
    ]
