# Generated by Django 5.0.4 on 2024-04-08 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0002_rename_description_term_definition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='aspect',
            field=models.TextField(choices=[('biological_process', 'biological_process'), ('cellular_component', 'cellular_component'), ('molecular_function', 'molecular_function')]),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(db_index=True, max_length=255)),
                ('term1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation1', to='go.term')),
                ('term2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation2', to='go.term')),
            ],
            options={
                'unique_together': {('term1', 'relation', 'term2')},
            },
        ),
    ]
