# Generated by Django 5.0.4 on 2024-04-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0005_term_uniprot_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='aspect',
            field=models.TextField(choices=[('cellular_component', 'cellular_component'), ('biological_process', 'biological_process'), ('molecular_function', 'molecular_function')]),
        ),
    ]
