# Generated by Django 5.0.4 on 2024-04-30 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0022_alter_term_aspect'),
        ('uniprot', '0004_remove_entry_keywords_entry_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='aspect',
            field=models.TextField(choices=[('biological_process', 'biological_process'), ('molecular_function', 'molecular_function'), ('cellular_component', 'cellular_component')]),
        ),
        migrations.AlterField(
            model_name='termuniprotentry',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniprot_associations', to='go.term'),
        ),
        migrations.AlterField(
            model_name='termuniprotentry',
            name='uniprot_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='go_associations', to='uniprot.entry'),
        ),
    ]
