# Generated by Django 5.0.4 on 2025-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0034_alter_term_aspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='aspect',
            field=models.TextField(choices=[('cellular_component', 'cellular_component'), ('molecular_function', 'molecular_function'), ('biological_process', 'biological_process')]),
        ),
    ]
