# Generated by Django 5.0.4 on 2025-06-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0044_alter_term_aspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='aspect',
            field=models.TextField(choices=[('biological_process', 'biological_process'), ('cellular_component', 'cellular_component'), ('molecular_function', 'molecular_function')]),
        ),
    ]
