# Generated by Django 5.0.4 on 2025-07-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0003_relation'),
        ('go', '0045_alter_term_aspect'),
        ('uniprot', '0016_entry_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='aspect',
            field=models.TextField(choices=[('molecular_function', 'molecular_function'), ('cellular_component', 'cellular_component'), ('biological_process', 'biological_process')]),
        ),
        migrations.AddIndex(
            model_name='termuniprotentry',
            index=models.Index(fields=['uniprot_entry_id', 'term_id', 'qualifier', 'eco_term_id'], name='go_termunip_uniprot_3c4e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='termuniprotentry',
            index=models.Index(fields=['uniprot_entry_id'], name='go_termunip_uniprot_d2f363_idx'),
        ),
    ]
