# Generated by Django 5.0.4 on 2025-09-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0048_alter_term_aspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='aspect',
            field=models.TextField(choices=[('cellular_component', 'cellular_component'), ('biological_process', 'biological_process'), ('molecular_function', 'molecular_function')]),
        ),
    ]
